### ISSUE TITLE
Global styles defined in layouts do not update after first switch

### ISSUE THREAD

**Issue by danrocha** [maoberlehner/dynamic-vue-layout-components#2]
# Description 

In the case my layout files define different global styles (for example, change the background and text colors), the change works as expected in the first layout switch, but then stays fixed on subsequente switches.

# Reproduction

https://codesandbox.io/s/vue-template-bf6ox?fontsize=14

- Switch to "books"
- The background and color changes according to the styles defined on `booksLayout.vue`
- Switch back to "movies"
- The background and color stays as defined in `booksLayout.vue`, ignoring the new definitions on `moviesLayout.vue`

**Comment by maoberlehner** [comment]
Yeah, that's kinda as expected if you're applying global styles in components. You either have to [scope](https://vue-loader.vuejs.org/guide/scoped-css.html) your styles or use CSS modules.

If you have further questions please head over to https://forum.vuejs.org/ because this is not specific to this repository. Thx!
